services:
  api:
    build: ./EduPath_backend
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - COURSES_BASE_PATH=/app/courses_files
    volumes:
      - ./EduPath_backend/Edupath_backend.API/appsettings.json:/app/appsettings.json
      - ./EduPath_backend/courses_files:/app/courses_files

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  frontend:
    build: 
      dockerfile: Docker/Dockerfile
      context: ./EduPath_frontend
      args:
        - VITE_API_URL=http://localhost:5000/api
  
    ports:
      - "3000:80"
    depends_on:
      - api
